name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with: 
          command: npx cypress run
          browser: chrome
